services:
  ctf1:
    build: .
    image: debian-ssh
    container_name: ctf1
    hostname: ctf1
    ports:
      - "5001:22"
    restart: unless-stopped
    networks:
      ctf_net:
        ipv4_address: 172.28.0.11

  ctf2:
    build: .
    image: debian-ssh
    container_name: ctf2
    hostname: ctf2
    ports:
      - "5002:22"
    restart: unless-stopped
    networks:
      ctf_net:
        ipv4_address: 172.28.0.12

networks:
  ctf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
